repos:
  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
        language_version: python3
        files: ^src/

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120", "--ignore=E203,W503,E501,E722,F841,F401", "--select=E9,F63,F7,F82"]
        files: ^src/

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.2
    hooks:
      - id: bandit
        args: ["-r", "src/"]
        files: ^src/